---
title: "Reproducible Research: Peer Assessment 1"
author: Alex Pittendreigh
date: "17 October 2014"
output: 
  html_document:
    keep_md: true
---

## Introduction ##

It is now possible to collect a large amount of data about personal movement activity monitoring devices such as a [Fitbit](http://www.fitbit.com), [Nike Fuelband](http://www.nike.com/us/en_us/c/nikeplus-fuelband) or [Jawbone Up](http://jawbone.com/up). However, the data generated by these devises tend to remain under-utilised because the data is hard to obtain and/or there is a lack of statistical methods and software for processing and interpreting this data.

This assessment will use a small sampling of data from one such device to answer questions regarding the activity performed over a two month period.

## Data ##

The device collects data at 5 minute intervals throughout the day and consists of two months of data from an anonymous individual gathered during the months of October and November in 2012. The original data set is located at [https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip) as at the 17th October 2014, however, this analysis will used the file provided in the Github repo provided by Dr Peng and is named **activity.zip**. The extracted raw data file from this archive is a comma separated value file called **activity.csv** and consists of 3 variables and 17568 observations.

The columns in this raw data set are:

1. **steps**: The number of steps taken in a 5 minute period with missing data indicated with NA
2. **date**: Dates of the recorded activity in the form of "YYYY-MM-DD"
3. **interval**: Identifier for the 5 minute interval in which the measurement was taken

This analysis assumes that the raw data file exists and that you have manually extracted in contents into the current working directory.

## Goal of Analysis ##

The broad questions that this analysis will answer are:

1. What is the mean total number of steps taken each day?
2. What is the average daily activity pattern?
3, Are there differences in activity patterns between weekdays and weekends?

This analysis will answer eaxh of these questions in order and provide a number of tables and plots,

## Analysis ##

### Loading and Preprocessing Data ###

Firstly we need to load the data and to see what kind of shape it is in...

